services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      target: dev
    container_name: api-gateway
    ports:
      - 3000:3000
    depends_on:
      - auth
    env_file:
      - ./api-gateway/.env.dev
    develop:
      watch:
        - path: ./api-gateway/
          target: /app/
          action: sync
        - path: ./api-gateway/package.json
          action: rebuild

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
      target: dev
    container_name: auth
    depends_on:
      - mongo-database-auth
    env_file:
      - ./auth/.env.dev
    develop:
      watch:
        - action: sync
          path: ./auth/
          target: /app/
        - action: rebuild
          path: ./auth/package.json

  mongo-database-auth:
    image: mongo:latest
    container_name: mongo-database-auth
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo-auth-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    container_name: client
    depends_on:
      - api-gateway
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env.dev
    develop:
      watch:
        - action: sync
          path: ./client/
          target: /app/
        - action: rebuild
          path: ./client/package.json
volumes:
  mongo-auth-volume:
